name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Install GNU Guix
      uses: PromyLOPh/guix-install-action@v1

    - name: Cache Guix Manifest
      id: guix-cache
      uses: actions/cache@v4
      with:
        path: guix-manifest-cache
        key: guix-manifest-${{ runner.os }}-${{ hashFiles('channels.scm', 'manifest.scm') }}

    - name: Restore Guix Cache
      if: steps.guix-cache.outputs.cache-hit == 'true'
      run: |
        sudo guix archive --authorize < guix-manifest-cache/signing-key.pub
        guix archive --import < guix-manifest-cache/manifest.nar

    - name: Guix Build
      run: guix time-machine -C channels.scm -- build -f guix.scm

    - name: Run Lints
      run: guix time-machine -C channels.scm -- shell -m manifest.scm -- cargo clippy -- -D warnings

    - name: Run Tests
      run: guix time-machine -C channels.scm -- shell -m manifest.scm -- cargo test

    - name: Save Guix Cache
      if: steps.guix-cache.outputs.cache-hit != 'true'
      run: |
        mkdir -p guix-manifest-cache
        OUTPUTS=$(guix time-machine -C channels.scm -- build -m manifest.scm)
        guix archive --export -r $OUTPUTS > guix-manifest-cache/manifest.nar
        # signing key is generated by guix-install-action
        cp /etc/guix/signing-key.pub guix-manifest-cache/
