name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout project
      uses: actions/checkout@v4

    - name: Install GNU Guix
      uses: PromyLOPh/guix-install-action@v1
      with:
        pullAfterInstall: false

    - name: Cache Guix Manifest NAR
      id: guix-cache
      uses: actions/cache@v4
      with:
        path: guix-manifest-cache
        key: guix-manifest-${{ runner.os }}-${{ hashFiles('channels.scm', 'manifest.scm') }}

    - name: Restore Guix Manifest NAR
      if: steps.guix-cache.outputs.cache-hit == 'true'
      run: |
        sudo guix archive --authorize < guix-manifest-cache/signing-key.pub
        guix archive --import < guix-manifest-cache/manifest.nar

    - name: Install Dev Environment
      run: |
        set -euo pipefail
        guix pull -C channels.scm
        guix package -m manifest.scm

    - name: Guix Build
      run: guix build -f guix.scm

    - name: Run Lints
      run: cargo clippy -- -D warnings

    - name: Run Tests
      run: cargo test

    - name: Save Guix Manifest NAR
      if: steps.guix-cache.outputs.cache-hit != 'true'
      run: |
        mkdir -p guix-manifest-cache
        OUTPUTS=$(guix build -m manifest.scm)
        guix archive --export -r $OUTPUTS > guix-manifest-cache/manifest.nar
        # signing key is generated by guix-install-action
        cp /etc/guix/signing-key.pub guix-manifest-cache/
